used verifyIfLoggedIn

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -65,3 +65,25 @@ jobs:
 
       - name: Test
         run: go test -v ./...
+
+  generate:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: '1.20'
+
+      - name: Generate
+        run: go generate ./...
+
+      - name: Check for changes
+        run: |
+          if [[ `git status --porcelain` ]]; then
+            echo "::error::Go generate has modified some files:"
+            git status --porcelain
+            git diff
+            exit 1
+          fi
